### ISSUE TITLE
Multifield output

### ISSUE THREAD

**Issue by NicktheGeek** [wpengine/atlas-content-modeler#197]
### Is your feature request related to a problem? Please describe.
I registered a field for use with outputting staff details. This will be output on the front end as a list. Ideally I'd be able to get this data as an array of strings. For now I have to receive it, then split the string on `\r\n` so I can output it as a list in the component. 

### Describe the solution you'd like
An option in text areas to return the multiline output as an array of strings or a repeater field that can generate nodes.

### Describe alternatives you've considered
Using multiline and splitting the output to get my array.

**Comment by nickcernis** [comment]
Thanks for the suggestion, Nick.

Can you share examples about what these “staff details” look like? It would help us to better understand the use case here.

Is there a reason they're being modelled as a single multiline field with freeform entry as opposed to multiple separate text (or other) fields, one for each relevant staff detail?

We had [repeater fields](https://github.com/wpengine/atlas-content-modeler/pull/40) in an earlier version that would let you enter repeated input in separate “rows”, but we [removed them](https://github.com/wpengine/atlas-content-modeler/pull/124) after user and product owner feedback while we consider other approaches (such as relationship fields).

**Comment by NicktheGeek** [comment]
@nickcernis in this case it is open ended. There aren't a fixed number of "details"

## Staff Person 1
- detail 1
- detail 2
- detail 3
- detail 4
- detail 5

## Staff Person 2
- Different detail 1
- Different detail 2
- Different detail 3

These aren't really specific. There could be 1 detail, there could be 10.

**Comment by nickcernis** [comment]
Great, thank you — that helps!

**Comment by mtedwards** [comment]
Are you considering adding repeater fields back in the future?

**Comment by nickcernis** [comment]
@mtedwards We have a Relationship field in development now that we think satisfies a lot of cases where repeaters are currently used. It will let you attach one or more entries from another model, and eventually add new entries to the other model from the current entry — effectively behaving like repeaters do now but backed by their own model/post type.

One advantage of relationship fields over repeaters is that the "repeated" data becomes part of another post type that you can independently pull from and query against. We'll store the references in their own table so you can efficiently query forward and back-references.

We plan to look at ways of repeating individual fields (media/strings) as requested in this issue, because the use cases for things like image galleries and “feature lists” are clear, but I don't have a timeline for that work yet.

**Comment by nickcernis** [comment]
Tracking internally at https://wpengine.atlassian.net/browse/MTKA-1301.

**Comment by anthonyburchell** [comment]
Hey @NicktheGeek ! Great news! Yesterday we launched text repeaters that will accomplish what you were looking for in this issue. We have support for both single line and multi line repeaters. 😎 


<img width="979" alt="ACM-text-repeaters-wp-editor" src="https://user-images.githubusercontent.com/11888980/152192034-b9108038-04b5-42a9-8c3f-40446a30988c.png">
<img width="667" alt="ACM-text-repeaters-endpoint" src="https://user-images.githubusercontent.com/11888980/152192030-cfb73b6e-ea4a-469b-a554-1333b278b74e.png">


Going to close this issue but feel free to reopen if we didn't hit the goal. :D
