### ISSUE TITLE
Make 'slug' appear in Quick Edit for public models

### ISSUE THREAD

**Issue by jasonbahl** [wpengine/atlas-content-modeler#520]
A clear and concise description of the bug goes here.

### To reproduce
1. Create an ACM Model
2. Add content to the model
3. Try to edit the slug

### Expected behavior
In core WordPress post types, there's a UI to edit slugs. 

With ACM models there's no way to edit the slug once it's been set. 

I would like to be able to edit the slug.

#### Post Type registered with the following code: 

```php
	register_post_type( 'custom_rabbit', [
		'label' => 'Custom Rabbit',
		'show_ui' => true,
		'public' => true,
		'show_in_graphql' => true,
		'show_in_rest' => true,
		'graphql_single_name' => 'CustomRabbit',
		'graphql_plural_name' => 'CustomRabbits',
	]);
```

I can edit the slug while editing the post

![CleanShot 2022-05-05 at 15 28 17](https://user-images.githubusercontent.com/1260765/167028568-891e32e9-d3bf-44f7-a241-b03c092a5a0a.png)

I can edit the slug in quick edit

![CleanShot 2022-05-05 at 15 27 41](https://user-images.githubusercontent.com/1260765/167028525-ba7d8949-f7bd-4d03-96ec-50c464c6af17.png)

----

#### Post Type registered using ACM:

I can't edit the slug on the edit view

![CleanShot 2022-05-05 at 15 29 54](https://user-images.githubusercontent.com/1260765/167028755-c0551a14-c0f0-41d6-bc67-fdaf88f22161.png)

I can't edit the slug in quick edit

![CleanShot 2022-05-05 at 15 29 36](https://user-images.githubusercontent.com/1260765/167028722-6cefb43f-ff77-4a74-9215-4a762c243fda.png)

### Version information
- Plugin version: 0.17.0
- WordPress version: 5.9.3

**Comment by nickcernis** [comment]
@jasonbahl On the edit view, you should be able to enable the slug meta box via Screen Options:

<img width="1329" alt="Screenshot 2022-05-06 at 10 15 18" src="https://user-images.githubusercontent.com/647669/167094051-7ac7413a-bba7-4857-ba07-59dbd1b2e02a.png">

Perhaps we should enable it by default, though.

The fact that it's missing on the quick edit view is a bug, though. ([Core suggests the slug should appear for any publicly_queryable CPT](https://github.com/WordPress/WordPress/blob/a34abb93b75850c15be2e70649846055d97858e5/wp-admin/includes/class-wp-posts-list-table.php#L1634-L1641) — i.e. if “API visibility” is 'true' in ACM, which isn't working.)

I tracked it down to here, where we're disabling titles so that they don't appear on the edit screen:

https://github.com/wpengine/atlas-content-modeler/blob/8fa0a296754a06be2cca6e38d400076c4a495454/includes/publisher/class-publisher-form-editing-experience.php#L93-L96

We need to adjust that logic to run only on edit/create screens and not on the post list view. I added this to Jira for us to fix. https://wpengine.atlassian.net/browse/MTKA-1495

**Comment by mindctrl** [comment]
Since ACM has entered an end-of-life phase and won't be receiving any new features like this, I'm going to close this issue. Source: https://github.com/wpengine/atlas-content-modeler/blob/main/docs/end-of-life/index.md
