### ISSUE TITLE
Make title and slug appear in Quick Edit for public models

### ISSUE THREAD

**Issue by marlonjet** [wpengine/atlas-content-modeler#565]
A clear and concise description of the bug goes here.

### To reproduce
1. Create an ACM Model
2. Add content to the model
3. Add content to the model

### Expected behavior
Once created the content it automatically adds a random title which I can't edit on Quick Edit same for the slug

### Screenshots
![image](https://user-images.githubusercontent.com/97437607/173048424-b70e3b29-686b-4efd-b98c-814ad4e73451.png)
![image](https://user-images.githubusercontent.com/97437607/173048495-5d3cce5f-7582-4826-8712-52ea2844f7e3.png)

### Version information
- Plugin version:  0.17.0
- WordPress version: 6.0
- Operating system: IOS
- Browser: Google Chrome

**Comment by nickcernis** [comment]
Thank you for the report, @marlonjet!

We're tracking a similar issue with quick edits at https://github.com/wpengine/atlas-content-modeler/issues/520 for the slug, so we could work on these together.

> Once created the content it automatically adds a random title…

You can set tick “Use this field as the entry title” on a text field in your model to be able to set model titles. (This still doesn't expose them to quick edit yet, but it at least lets you set the title instead of gaining a title based on the post ID.)

**Comment by mindctrl** [comment]
Thanks for the request. Since ACM has entered an end-of-life phase and won't be receiving any new features like this, I'm going to close this issue. Source: https://github.com/wpengine/atlas-content-modeler/blob/main/docs/end-of-life/index.md
