### ISSUE TITLE
Related model shown as empty string when using REST (fetch) to access

### ISSUE THREAD

**Issue by felizuno** [wpengine/atlas-content-modeler#647]
I have a public model with relationships to other public models, for example an album that has relationships to individual songs. If I request `myapp.local/wp-json/wp/v2/albums` then I will receive `<album>.acm_fields.songs: ""` which is not an array and doesn't indicate the related foreign keys. 

### To reproduce
1. Make a model relationship between two ACM models
2. Query one of the model types using `fetch()` instead of the GQL tools
3. Explore the response data, note that relationships have values of `""` and are neither arrays nor indicate the related models

### Expected behavior
Relationships should return an array (at least *-to-many relationships should), and that array should contain the IDs or some other foreign key to enable me to re-create the relationship in the client.

### Version information
- Plugin version: 0.23.0
- WordPress version: 6.1.1
- Operating system: all
- Browser: all

### Additional context
I'm having to use fetch is because the GraphQL implementation is far away from production readiness and we are having to abandon our current adoption of it and move to REST. This is specifically because optional relationships are always modeled as non-nullable by the tooling.

If this does not work we will have to completely move off ACM and throw away thousands of dollar of work.

**Comment by felizuno** [comment]
Alongside this issue I would like to comment that it is NOT INDICATED CLEARLY ENOUGH that these tools are not production ready in the WPEngine marketing content. I would go so far as to say that even describing the tools as in "beta" is too generous considering there are such large gaps in such core functionality.

**Comment by mindctrl** [comment]
@felizuno thanks for this report. Please accept my apologies for the inconvenience.

For context, the relationships used to work in WPGraphQL, but a change in WPGraphQL 1.13.x broke those queries. We never did add full relationship data to REST, as we pivoted our focus to GraphQL. We should have documented that to avoid any confusion and wasted effort, and we'll do that until we can address the REST shortcomings.

In the meantime, we're going to fix the issue with the WPGraphQL integration so that the relationship queries work as expected. You can follow #643 for updates on that. I'll leave this open to track the REST API issue you raised.

**Comment by felizuno** [comment]
@mindctrl I have to ask - is this project still under real active development? I see the bug fix in flight (thank you) but I also see that while there are reviewers participating you seem to be the only active contributor these days, and the last feature (non bug/chore) work appears to have happened in November.

I know that the economy is rough (it is for us too which makes these wasted dev cycles extra painful) and companies are having to shift resources on short notice, but if you no longer have the dev support you need to fulfill the advertised features/benefits and are simply keeping the lights on and fixing bugs then I think you should dramatically change how you are advertising these tools to the public.

If you haven't looked in a while please review the way that ACM, Faust, and other tools are being advertised to the public by WPEngine, and notice that not only is the Beta (in my opinion Alpha) status not mentioned, but the tone of the marketing is not appropriate for software that is not under active development.

I don't want to make this personal because I doubt it's your fault/has anything to do with you or the engineering org. I've been around what feels like a thousand different product/marketing people who insist on misrepresenting things  while simultaneously not investing the appropriate amount of dev support to make sure they can meet the expectations they set. I've spiked sprints and epics to focus on business critical work and never returned to them. I'm sure that there are other fires that are constantly popping up that are taking people off the line on these tools. But I do want to appeal to you personally, engineer to engineer, that the state of these tools compared to how they are represented is completely inappropriate and must be changed. It's hurting others and it's hurting the WPEngine brand (our agency removed it from our list of approved technologies until further review this morning, and that decision was out of my hands as engineering director).

**Comment by mindctrl** [comment]
@felizuno, I appreciate your candid feedback. Thank you for taking the time to share. We've been focused on integrating ACF into WP Engine since [acquiring it last year](https://wpengine.com/blog/wp-engine-acquires-delicious-brains-plugins-including-advanced-custom-fields/). The ACF team is currently working to bring feature parity with ACM. Custom post types and custom taxonomies are coming soon to ACF, and the WPGraphQL for ACF plugin is getting an update too. I don't have an ETA just yet, but the work is pretty far along and we'll be making some announcements soon.

**Comment by felizuno** [comment]
@mindctrl I have no idea what you are referring to - I was specifically referring to ACM as not even close to ready and you're telling me how you're working on ACF? 

We switched away from ACM to ACF and it is working much better, as at least it does what its documentation claims it does.

It you have no ETA on when things are going to be ready then stop advertising them as already ready. At this point people have lost their jobs and we're actively losing money on a project from having to switch away from ACM.

**Comment by mindctrl** [comment]
ACM has entered an end-of-life phase. As such we have no plans to further develop the REST API aspects of the plugin. Closing this now. 😞
